backend:
  name: github
  repo: <% GITHUB_REPOSITORY %> # Gulp will replace this with your GitHub repository
  branch: master # Branch to update (master by default)

media_folder: "src/assets/img/content" # Folder where user uploaded files should go

collections: # A list of collections the CMS should be able to edit
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/_pages/home.md"
        label: "Homepage"
        name: "home"
        fields:
          - {label: Title, name: title, widget: string}
      - file: "src/_pages/404.md"
        label: "404a"
        name: "404a"
        fields:
          - {label: Title, name: title, widget: string}
      - file: "src/pages/home.md"
        label: "404b"
        name: "404b"
        fields:
          - {label: Title, name: title, widget: string}